const ACTION_TYPE = {
    SIGNUP_LOADING: 'SIGNUP_LOADING',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',
    SIGNUP_ASYNC: 'SIGNUP_ASYNC',
    SET_LOGIN_STATE :"SET_LOGIN_STATE",
    LOGIN_LOADING: 'LOGIN_LOADING',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_ASYNC: 'LOGIN_ASYNC',
  };
  
  export default ACTION_TYPE;